version: "3"

services:
  mysql-films-db:
    image: mysql
    container_name: mysql-films-db
    environment:
      MYSQL_ROOT_PASSWORD: SimplonRoot2023!
      MYSQL_DATABASE: filmsdb
      MYSQL_USER: snoopy
      MYSQL_PASSWORD: snoopy123!
    ports:
      - "3306:3306"
    volumes:
      - mysql-films-db:/var/lib/mysql
volumes:
  mysql-films-db:
